name: Pull Rules from GCS and Deploy to Firebase Hosting

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Optional: run every 5 min

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPFIG_DEV }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: appfig-dev

      - name: Pull latest rule files from Firebase Storage
        run: |
          mkdir -p rules/tenants
          gsutil -m cp gs://appfig-dev.firebasestorage.app/rules-current.json rules/
          gsutil -m cp gs://appfig-dev.firebasestorage.app/manifest.json rules/
          gsutil -m cp -r gs://appfig-dev.firebasestorage.app/tenants/* rules/tenants/

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
